config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection  do
        get 'get_category_children'
        get 'get_category_grandchildren'
      end
  end
  root 'products#index'
  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/identification', to: 'users#edit', as: :identification
  get 'users/exhibiting', to: 'users#edit', as: :exhibiting
  get 'users/profile', to: 'users#edit', as: :profile
  get 'users/logout', to: 'users#edit', as: :logout
  get 'users/show', to: 'users#edit', as: :show
  get 'users/signup', to: 'users#edit', as: :signup

    
  resources :users, only: [:show] 
  resources :payments, only: [:new, :show] do
    collection do
      post 'show', to: 'payments#show'
      post 'pay', to: 'payments#pay'
      post 'delete', to: 'payments#delete'
    end
  end

  # resources :purchase, only: [:index] do
  #   collection do
  #     get 'index', to: 'purchase#index'
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
  resources :signup,only: [:create] do
    collection do
      get 'member'
      get 'tell'
      get 'address'
      get 'pay' # ここで、入力の全てが終了する
      get 'completion' # 登録完了後のページ
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def member
    @user = User.new
  end

  def tell
    session[:nickname] = user_params[:nickname]
    session[:family_name] = user_params[:family_name]
    session[:first_name] = user_params[:first_name]
    session[:family_name_kana] = user_params[:family_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:year] = user_params[:year]
    session[:month] = user_params[:month]
    session[:day] = user_params[:day]
    @user = User.new
  end

  def address
    session[:tell] = user_params[:tell]
    @address = StreetAddress.new
  end

  def pay
    
  end

  def completion
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  def create
    @address = StreetAddress.new(address_params)
    if session[:password] == "" #sns登録なら
      session[:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
      session[:password_confirmation] = "Devise.friendly_token.first(6)"
    else #email登録なら
      
    end
    @user = User.new(
      nickname: session[:nickname],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_name_kana: session[:family_name_kana],
      first_name_kana: session[:first_name_kana],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      year: session[:year],
      month: session[:month],
      day: session[:day],
      tell: session[:tell]
    )
    if @user.save 
      session[:id] = @user.id
      @user.seller_id = @user.id
      @user.buyer_id = @user.id
      @address.update(user_id:  @user.id)
      SnsCredential.update(user_id:  @user.id)
      if @address.save
        redirect_to completion_signup_index_path
      else
        redirect_to "/users/signup"
      end
    else
      redirect_to "/users/signup"
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :nickname, 
      :family_name, 
      :first_name, 
      :family_name_kana, 
      :first_name_kana, 
      :year,
      :month,
      :day,
      :tell,
      :email, 
      :password, 
      :password_confirmation)
  end

  def address_params
    params.require(:street_address).permit(
      :prefecture,
      :city,
      :postal_code,
      :building_name,
      :address,
      :address_family_name,
      :address_first_name,
      :address_family_name_kana,
      :address_first_name_kana,
      :address_tell,
      :user_id
    )
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/address.html.haml
= render "shared/logoheader"
.address-container
  = form_for @address, url: signup_index_path, method: :post do |f|
    .address-container__header
      住所入力
    .address-container__content
      .address-container__content__form-group
        %label お名前
        %span.form-required 必須
        = f.text_field :address_family_name, class: "identification-input", placeholder: "例）山田"
        = f.text_field :address_first_name, class: "identification-input", placeholder: "例）彩"
      .address-container__content__form-group
        %label お名前カナ
        %span.form-required 必須
        = f.text_field :address_family_name_kana, class: "identification-input", placeholder: "例）ヤマダ"
        = f.text_field :address_first_name_kana, class: "identification-input", placeholder: "例）アヤ"
      .address-container__content__form-group
        %label 郵便番号
        %span.form-required 必須
        = f.text_field :postal_code, class: "identification-input", placeholder: "例）123-4567"
      .address-container__content__form-group
        %label 都道府県
        %span.form-required 必須
      .identification-select-wrap
        = f.collection_select :prefecture, Prefecture.all, :id, :name, {}, class: "identification-input"
        = icon "fas", "angle-down 2x"
      .address-container__content__form-group
        %label 市区町村
        %span.form-required 必須
        = f.text_field :city, class: "identification-input", placeholder: "例）横浜市緑区"
      .address-container__content__form-group
        %label 番地
        %span.form-required 必須
        = f.text_field :address, class: "identification-input", placeholder: "例）青山1-1-1"
      .address-container__content__form-group
        %label 建物名
        %span.form-arbitrary 任意
        = f.text_field :building_name, class: "identification-input", placeholder: "例）柳ビル103"
      .address-container__content__form-group
        %label 電話
        %span.form-arbitrary 任意
        = f.text_field :address_tell, class: "identification-input", placeholder: "例）09012345678"
    .address-container__btn-next
      = f.submit "次へ進む", class:"address-btn", type:"submit"
= render "shared/logofooter"

app/views/signup/completion.html.haml
= render "shared/logoheader"
.completion-container
  .completion-container__header
    .completion-container__header__text
      会員登録完了
  .completion-container__notice
    .completion-container__notice__text
      ありがとうございます。
      %br
      会員登録が完了しました。
  .completion-container__btn
    %button{class:"start-btn", type:"submit"}
      = link_to "メルカリをはじめる",root_path, class: "link_white"
  .completion-container__banner
    = render "users/footer-top"
= render "shared/logofooter"

app/views/signup/member.html.haml
.sign-up_container
  = render "shared/logoheader"
  .sign-up_main
    .sign-up_main-container
      .sign-up_main-container-head
        会員情報入力
      .sign-up_main-container_registration
        = form_for @user, url: tell_signup_index_path, method: :get do |f|
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                ニックネーム
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "例)メルカリ"
            .sign-up_main-container_registration-content-form
              = f.label :email do
                メールアドレス
              %span{class: "form-require"}必須
              = f.text_field :email, class: "input-default", placeholder: "PC・携帯どちらでも可"
            .sign-up_main-container_registration-content-form
              = f.label :password do
                パスワード
              %span{class: "form-require"}必須
              = f.text_field :password, class: "input-default", placeholder: "7文字以上"
            .sign-up_main-container_registration-content-form
              = f.label :password_confirmation do
                パスワード(確認)
              %span{class: "form-require"}必須
              = f.text_field :password_confirmation, class: "input-default", placeholder: "7文字以上"
            .sign-up_main-container_registration-content-form
              %h3 本人確認
              %div{class: "form-text"} 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .sign-up_main-container_registration-content-form
              %div
                = f.label :family_name do
                  お名前(全角)
                %span{class: "form-require"}必須
              = f.text_field :family_name, class: "input-default-half", placeholder: "例)山田"
              = f.text_field :first_name, class: "input-default-half", placeholder: "例）彩"
            .sign-up_main-container_registration-content-form
              %div
                = f.label :family_name_kana do
                  お名前カナ(全角)
                %span{class: "form-require"}必須
              = f.text_field :family_name_kana, class: "input-default-half", placeholder: "例)ヤマダ"
              = f.text_field :first_name_kana, class: "input-default-half", placeholder: "例)アヤ"
            .sign-up_main-container_registration-content-form
              = f.label :year do
                生年月日
              %span{class: "form-require"}必須
              .birthday-select
                .birthday-select-wrap
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :year, ["--", "2019", "2018", "2017", "2016", "2015"], {}, class: "select"
                %span 年
                .birthday-select-wrap{class: "birthday-select-wrap_month"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :month, ["--", "1", "2", "3", "4", "5", "6", "7"],{}, class: "select"
                %span 月
                .birthday-select-wrap{class: "birthday-select-wrap_day"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :day, ["--", "1", "2", "3", "4", "5", "6", "7"],{}, class: "select"
                %span 日
            .sign-up_main-container_registration-content-form-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              .sign-up_main-container_registration-content-form-text-center
                「次へ進む」のボタンを押すことにより、
                = link_to "", class: "form-text-blue" do
                  利用規約
                に同意したものとみなします
            = f.submit "次へ進む", class: "submit-btn"
            .sign-up_main-container_registration-content-form
              %p
                = link_to "", class: "form-text-blue" do
                  本人情報の登録について
                  = icon "fas", "arrow-right"
  = render "shared/logofooter"

app/views/signup/pay.html.haml
.sign-up_container
  = render "shared/logoheader"
  .sign-up_main
    .sign-up_main-container
      .sign-up_main-container-head
        支払い方法
      .sign-up_main-container_registration
        = form_with method: :get, id: "#charge-form" ,local:true do |f|
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                カード番号
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "半角数字のみ", id: "card_number", name: "number"
              = image_tag src= "https://www.sbpayment.jp/images/service/card.png", width: "300", height: "45"
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                有効期限
              %span{class: "form-require"}必須
              .birthday-select
                .birthday-select-wrap{class: "birthday-select-wrap_month"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :month, ["--", "1", "2", "3", "4", "5", "6", "7","8", "9", "10", "11", "12"], { class: "select" ,id:"exp_month",name: "exp_month"}
                %span 月
                .birthday-select-wrap{class: "birthday-select-wrap_year"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :year, ["--", "19", "20", "21", "22", "23", "24", "25"], { class: "select" ,id:"exp_year",name: "exp_year"}
                %span 年
            .sign-up_main-container_registration-content-form{class: "bottom"}
              = f.label :nickname do
                セキュリティーコード
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "カード背面4桁もしくは3桁の番号",id: "payment_card_cvc",name:"cvc"
            .sign-up_main-container_registration-content-form
              %p
                = link_to "", class: "form-text-blue" do
                  = icon "fas", "question-circle"
                  カード裏面の番号とは？
            .sign-up_main-container_registration-content-form
              = f.submit "次へ進む", class: "submit-btn",id: "token_submit"
  = render "shared/logofooter"

app/views/signup/tell.html.haml
= render "shared/logoheader"
.tell-container
  .tell-container__width-box
    .tell-container__width-box__header
      .tell-container__width-box__header__tell
        電話番号の確認
    = form_for @user, url: "/signup/address", method: :get do |f|
      .tell-container__width-box__form__box
        .tell-container__width-box__form__box__content
          .tell-container__width-box__form__box__content__tell-box
            %h2.tell-container__width-box__form__box__content____tell-box__header
              携帯電話の番号
            = f.text_field :tell ,class:"tell-numbers-input", placeholder:"携帯電話の番号を入力"
            .tell-container__width-box__form__box__content__tell-box__message
              本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        .tell-container__width-box__form__box__btn-box
          = f.submit "SMSを送信する", class:"sms-send-btn"
        .tell-container__width-box__form__box__sms-message
          *電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .tell-container__width-box__footer
          =link_to "電話番号の確認が必要な理由>" ,id: "confirmation-reason"
= render "shared/logofooter"