config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection  do
        get 'get_category_children'
        get 'get_category_grandchildren'
      end
  end
  root 'products#index'
  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/identification', to: 'users#edit', as: :identification
  get 'users/exhibiting', to: 'users#edit', as: :exhibiting
  get 'users/profile', to: 'users#edit', as: :profile
  get 'users/logout', to: 'users#edit', as: :logout
  get 'users/show', to: 'users#edit', as: :show
  get 'users/signup', to: 'users#edit', as: :signup

    
  resources :users, only: [:show] 
  resources :payments, only: [:new, :show] do
    collection do
      post 'show', to: 'payments#show'
      post 'pay', to: 'payments#pay'
      post 'delete', to: 'payments#delete'
    end
  end

  # resources :purchase, only: [:index] do
  #   collection do
  #     get 'index', to: 'purchase#index'
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
  resources :signup,only: [:create] do
    collection do
      get 'member'
      get 'tell'
      get 'address'
      get 'pay' # ここで、入力の全てが終了する
      get 'completion' # 登録完了後のページ
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  has_many :transactions
  has_many :products, through: :transactions
  has_many :comments
  has_many :likes
  has_one :street_address
  has_one :payment
  has_many :evaluations
  has_many :sns_credentials, dependent: :destroy

  with_options presence: true do
    validates :family_name
    validates :first_name
    validates :family_name_kana
    validates :first_name_kana
    validates :nickname
    validates :password_confirmation
    validates :year
    validates :month
    validates :day
    validates :tell
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.where(id: snscredential.user_id).first
      unless user.present? #ユーザーが存在しないなら
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential

    else #sns登録 未
      user = User.where(email: auth.info.email).first
      if user.present? #会員登録 済
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else #会員登録 未
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    # hashでsnsのidを返り値として保持しておく
    return { user: user , sns_id: sns.id }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # binding.pry
    if @user.persisted? #userが存在したら
      SnsCredential.update(user_id: @user.id)
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else #userが存在しなかったら
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      render template: "devise/registrations/new" #redirect_to だと更新してしまうのでrenderで
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def new
    @user = User.new
  end

  # POST /resource
  def create
    binding.pry
    if params[:user][:password] == "" #sns登録なら
      params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
      params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
      super
      sns = SnsCredential.update(user_id:  @user.id)
    else #email登録なら
      super
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    render "users/#{params[:name]}"
    # , locals: {user: current_user }
  end


  def pay
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_exhibit.html.haml
.footer-sell-btn
  = link_to "/products/new" do
    %l 出品
    = icon "fas", "camera" , class:"fa-camera"

app/views/users/_header.html.haml
.header
  .header-inner
    .header-inner_top
      .header-inner_top-title
        = link_to "/products", class: "link" do
          %img{src: "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?273499512", width: "134", height: "36"}
      .header-inner_top-search
        = form_with url: products_path, class: "search", method: :get, local: true do |f|
          = f.label :search, class: "search" do
            = f.text_field :search, class:"search-form", placeholder: "何かお探しですか？"
            = link_to "", class: "link" do
              = icon  "fas", "search", class: "search-icon"
    .header-inner_bottom
      .header-inner_bottom-left
        .header-inner_bottom-left-category
          = link_to "", class: "link" do
            = icon "fas", "list", class: "icon-red"
            カテゴリーから探す
        .header-inner_bottom-left-brand
          = link_to "", class: "link" do
            = icon "fas","tags", class: "icon-red"
            ブランドから探す
      - if user_signed_in?
        .header-inner_bottom-right
          .header-inner_bottom-right-like
            = link_to "", class: "link" do
              = icon  "fas",'heart', class: "icon-grey"
              いいね！一覧
          .header-inner_bottom-right-news
            = link_to "", class: "link" do
              = icon  "fas",'bell', class: "icon-grey"
              お知らせ
          .header-inner_bottom-right-todo
            = link_to "", class: "link" do
              = icon  "fas",'check', class: "icon-grey"
              やることリスト
          .header-inner_bottom-right-mypage
            = link_to "/users/show", class: "link" do
              = icon  "far", 'user', class: "icon-grey"
              マイページ
      - unless user_signed_in?
        .header-inner_bottom-right
          .header-inner_bottom-right-signup
            = link_to signup_path, class: "signup" do
              新規会員登録
          .header-inner_bottom-right-login
            = link_to "/users/sign_in", class: "login" do
              ログイン

app/views/users/_sidebar.html.haml
.wrapper__mypage__container__l-side
  %nav
    %ul.mypage-nav-list
      %li.mypage-nav-list__item-active
        = link_to show_path , class: "mypage-nav-list__item-active__link" do
          マイページ
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          お知らせ
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          やることリスト
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          いいね！一覧
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to new_product_path , class: "mypage-nav-list__item__link" do
          出品する
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to exhibiting_path , class: "mypage-nav-list__item__link" do
          出品した商品-出品中
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          出品した商品-取引中
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          出品した商品-売却済み
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          購入した商品-取引中
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          購入した商品-過去の取引
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          ニュース一覧
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          評価一覧
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          ガイド
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          お問い合わせ
          = icon "fas", "angle-right"
      %h3.mypage-nav-list__double-header
        メルペイ
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          売上・振込申請
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          ポイント
          = icon "fas", "angle-right"
      %h3.mypage-nav-list__double-header
        設定
      %li.mypage-nav-list__item
        = link_to profile_path ,{controller: "users", action: "edit", name: "profile", class: "mypage-nav-list__item__link"} do
          プロフィール
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          発送元・お届け先住所
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to  payments_path,{controller: "payments", action: "show", name: "card", class: "mypage-nav-list__item__link"} do
          支払い方法
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          メール/パスワード
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to identification_path ,{controller: "users", action: "edit", name: "identification", class: "mypage-nav-list__item__link"} do
          本人情報
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to '' , class: "mypage-nav-list__item__link" do
          電話番号の確認
          = icon "fas", "angle-right"
      %li.mypage-nav-list__item
        = link_to logout_path ,{controller: "users", action: "edit", name: "logout", class: "mypage-nav-list__item__link"} do
          ログアウト
          = icon "fas", "angle-right"

app/views/users/completion.html.haml
= render "shared/logoheader"
.completion-container
  .completion-container__header
    .completion-container__header__text
      会員登録完了
  .completion-container__notice
    .completion-container__notice__text
      ありがとうございます。
      %br
      会員登録が完了しました。
  .completion-container__btn
    %button{class:"start-btn", type:"submit"}
      メルカリをはじめる
  .completion-container__banner
    = render "footer-top"
= render "shared/logofooter"

app/views/users/create.html.haml
.wrapper
  = render "header"
  .wrapper__breadcrumb
    パンくずエリア
  .identification-content
    .credit__container
      %h2.chapter__header 支払い方法
      .credit__container-inner
        %section
          %h3.credit__container-inner-content クレジットカード一覧
        %section.user__card
          %button.delete 削除する
          .user__card-info
            %span.image
            = image_tag src="/assets/Visa_Inc._logo.svg.png", size: "49x20"
            %br
            **** **** **** **** 
            %br
            05/24
        %section
          = link_to '/', class: "payment__box-content" do
            %span 支払い方法について
    =render "sidebar"        
  = render "footer"
  = render "exhibit"   

app/views/users/edit.html.haml
.wrapper
  = render "header"
  .wrapper__breadcrumb
    パンくずエリア
  .wrapper__profile
    .wrapper__profile__container
      .wrapper__profile__container__contents
        %h2.wrapper__profile__container__contents__header
          プロフィール
        %form.wrapper__profile__container__contents__content
          .wrapper__profile__container__contents__content__image-area
            %figure
              = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", alt: "画像"
            = text_field_tag "zip-name", "", class: "name-edit", placeholder: "例:)AYA☆セール中"
          .wrapper__profile__container__contents__content__profile-text
            %textarea.text-area{placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
            %button{class:"btn-default btn-red", type: "submit"}
              変更する

          
    = render "sidebar"
  = render "footer"
  = render "exhibit"

app/views/users/identification.html.haml
.wrapper
  = render "header"
  .wrapper__breadcrumb
    - breadcrumb :identification
    = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"
  .identification-content
    .identification-chapter-container
      .identification-chapter-head 本人情報の登録
      .identification-single-inner
        %p
          お客さまの本人情報をご登録ください。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .text-right
          = link_to "", class: "underline-opacity" do
            %span 本人確認書類のアップロードについて
            = icon "fas", "angle-right "
        .identification-form-group
          %label お名前
          %p
          =@user.family_name + @user.first_name
        .identification-form-group
          %label お名前カナ
          %p 
          =@user.family_name_kana + @user.first_name_kana
        .identification-form-group
          %label 生年月日
          %p 2019/08/25
        .identification-form-group
          %label 郵便番号
          %span.form-arbitrary 任意
          = text_field_tag "zip-name", "", class: "identification-input", placeholder: "例）123-4567"
        .identification-form-group
          %label 都道府県
          %span.form-arbitrary 任意
          .identification-select-wrap
            = select "prefecture", "", ["--", "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県",], {} ,{class: "identification-input"}
            = icon "fas", "angle-down 2x"
        .identification-form-group
          %label 市区町村
          %span.form-arbitrary 任意
          = text_field_tag "city", "", class: "identification-input", placeholder: "例) 大阪市"
        .identification-form-group
          %label 番地
          %span.form-arbitrary 任意
          = text_field_tag "adress1", "", class: "identification-input", placeholder: "例) 中央区難波5-1-60"
        .identification-form-group
          %label 建物名
          %span.form-arbitrary 任意
          = text_field_tag "adress2", "", class: "identification-input", placeholder: "例) なんばスカイオ"
        .identification-form-group
          = button_to "登録する", "", class: "btn-default btn-red"
          .identification-form-group.text-right
            = link_to "", class: "underline-opacity" do
              %span 本人情報の登録について  
              = icon "fas", "angle-right"
    =render "sidebar"        
  = render "footer"
  = render "exhibit"

app/views/users/index.html.haml
.wrapper
  = render "header"
  .wrapper__breadcrumb
    パンくずエリア
  .identification-content
    .identification-chapter-container
      .identification-chapter-head 本人情報の登録
      .identification-single-inner
        %p
          お客さまの本人情報をご登録ください。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        .text-right
          = link_to "", class: "underline-opacity" do
            %span 本人確認書類のアップロードについて
            = fa_icon "angle-right "
        .identification-form-group
          %label お名前
          %p 小田純也
        .identification-form-group
          %label お名前カナ
          %p オダジュンヤ
        .identification-form-group
          %label 生年月日
          %p 2019/08/25
        .identification-form-group
          %label 郵便番号
          %span.form-arbitrary 任意
          = text_field_tag "zip-name", "", class: "identification-input", placeholder: "例）123-4567"
        .identification-form-group
          %label 都道府県
          %span.form-arbitrary 任意
          .identification-select-wrap
            = select "prefecture", "", ["--", "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県", "石川県", "福井県", "山梨県", "長野県", "岐阜県", "静岡県", "愛知県", "三重県", "滋賀県", "京都府", "大阪府", "兵庫県", "奈良県", "和歌山県", "鳥取県", "島根県", "岡山県", "広島県", "山口県", "徳島県", "香川県", "愛媛県", "高知県", "福岡県", "佐賀県", "長崎県", "熊本県", "大分県", "宮崎県", "鹿児島県", "沖縄県",], {} ,{class: "identification-input"}
            = fa_icon "angle-down 2x"
        .identification-form-group
          %label 市区町村
          %span.form-arbitrary 任意
          = text_field_tag "city", "", class: "identification-input", placeholder: "例) 大阪市"
        .identification-form-group
          %label 番地
          %span.form-arbitrary 任意
          = text_field_tag "adress1", "", class: "identification-input", placeholder: "例) 中央区難波5-1-60"
        .identification-form-group
          %label 建物名
          %span.form-arbitrary 任意
          = text_field_tag "adress2", "", class: "identification-input", placeholder: "例) なんばスカイオ"
        .identification-form-group
          = button_to "登録する", "", class: "btn-default btn-red"
          .identification-form-group.text-right
            = link_to "", class: "underline-opacity" do
              %span 本人情報の登録について  
              = fa_icon "angle-right"
    =render "sidebar"        
  = render "footer"
  = render "exhibit"

app/views/users/member.html.haml
.sign-up_container
  = render "shared/logoheader"
  .sign-up_main
    .sign-up_main-container
      .sign-up_main-container-head
        会員情報入力
      .sign-up_main-container_registration
        = form_with url: "/users/member", method: :get, local: true do |f|
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                ニックネーム
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "例)メルカリ"
            .sign-up_main-container_registration-content-form
              = f.label :email do
                メールアドレス
              %span{class: "form-require"}必須
              = f.text_field :email, class: "input-default", placeholder: "PC・携帯どちらでも可"
            .sign-up_main-container_registration-content-form
              = f.label :password do
                パスワード
              %span{class: "form-require"}必須
              = f.text_field :password, class: "input-default", placeholder: "7文字以上"
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                パスワード(確認)
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "7文字以上"
            .sign-up_main-container_registration-content-form
              %h3 本人確認
              %div{class: "form-text"} 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .sign-up_main-container_registration-content-form
              %div
                = f.label :nickname do
                  お名前(全角)
                %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default-half", placeholder: "例)山田"
              = f.text_field :nickname, class: "input-default-half", placeholder: "例）彩"
            .sign-up_main-container_registration-content-form
              %div
                = f.label :nickname do
                  お名前カナ(全角)
                %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default-half", placeholder: "例)ヤマダ"
              = f.text_field :nickname, class: "input-default-half", placeholder: "例)アヤ"
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                生年月日
              %span{class: "form-require"}必須
              .birthday-select
                .birthday-select-wrap
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :birthday, ["--", "2019", "2018", "2017", "2016", "2015"], { class: "select" }
                %span 年
                .birthday-select-wrap{class: "birthday-select-wrap_month"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :birthday, ["--", "1", "2", "3", "4", "5", "6", "7"], { class: "select" }
                %span 月
                .birthday-select-wrap{class: "birthday-select-wrap_day"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :birthday, ["--", "1", "2", "3", "4", "5", "6", "7"], { class: "select" }
                %span 日
            .sign-up_main-container_registration-content-form-text
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              .sign-up_main-container_registration-content-form-text-center
                「次へ進む」のボタンを押すことにより、
                = link_to "", class: "form-text-blue" do
                  利用規約
                に同意したものとみなします
            = f.submit "次へ進む", class: "submit-btn"
            .sign-up_main-container_registration-content-form
              %p
                = link_to "", class: "form-text-blue" do
                  本人情報の登録について
                  = icon "fas", "arrow-right"
  = render "shared/logofooter"

app/views/users/new.html.haml
.wrapper
  = render "header"
  .wrapper__breadcrumb
    パンくずエリア
  .identification-content
    .large-content
      .logout-box
        .logout-box__btn
          =button_to "ログアウト","", class:"btn-default btn-red"
    =render "sidebar"        
  = render "footer"
  = render "exhibit"    

app/views/users/signup.html.haml
.registration__container
  = render "shared/logoheader"
  .registration__container__body
    %h2.registration__header 新規会員登録
    .registration__container__inner
      .l-single-content
        .mail-btn-red
          .fas.fa-envelope#icon
          = link_to "メールアドレスで登録する", member_signup_index_path, class: "mail-text"
        .facebook-btn-blue
          .fab.fa-facebook-square#icon
          = link_to "Facebookで登録する",user_facebook_omniauth_authorize_path, method: :post, class: "facebook-text"
        .google-btn-white
          %img{src: "https://yt3.ggpht.com/a/AGF-l78IIyXSWPuwMCI53MwhjOPlUrrFOx5laYc0ZA=s900-c-k-c0xffffffff-no-rj-mo",width: "25", height: "25",class:"googlelogo"}
          .google-text
            = link_to "Googleで登録する",user_google_oauth2_omniauth_authorize_path, method: :post
  = render "shared/logofooter"