config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection  do
        get 'get_category_children'
        get 'get_category_grandchildren'
      end
  end
  root 'products#index'
  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/identification', to: 'users#edit', as: :identification
  get 'users/exhibiting', to: 'users#edit', as: :exhibiting
  get 'users/profile', to: 'users#edit', as: :profile
  get 'users/logout', to: 'users#edit', as: :logout
  get 'users/show', to: 'users#edit', as: :show
  get 'users/signup', to: 'users#edit', as: :signup

    
  resources :users, only: [:show] 
  resources :payments, only: [:new, :show] do
    collection do
      post 'show', to: 'payments#show'
      post 'pay', to: 'payments#pay'
      post 'delete', to: 'payments#delete'
    end
  end

  # resources :purchase, only: [:index] do
  #   collection do
  #     get 'index', to: 'purchase#index'
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
  resources :signup,only: [:create] do
    collection do
      get 'member'
      get 'tell'
      get 'address'
      get 'pay' # ここで、入力の全てが終了する
      get 'completion' # 登録完了後のページ
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  require "payjp"


  def new
    @user = User.find(current_user.id)
    card = Payment.where(user_id: current_user.id)
  end

  def pay 
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_private_key]
    if params["payjpToken"].blank?
    redirect_to action: "show"
    else
      customer = Payjp::Customer.create(card: params["payjpToken"],metadata: {user_id: current_user.id})
      @card = Payment.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)

      if @card.save
        redirect_to action: "show"
        flash[:notice] = 'クレジットカードの登録が完了しました'
      else
        redirect_to action: "new"
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def delete 
    card = Payment.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = Rails.application.credentials.payjp[:payjp_private_key]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end


 def show 
  card = Payment.find_by(user_id: current_user.id)
  if card.blank?
    redirect_to action: "new" 
  else
    Payjp.api_key = Rails.application.credentials.payjp[:payjp_private_key]
    customer = Payjp::Customer.retrieve(card.customer_id)
    @default_card_information = customer.cards.retrieve(card.card_id)
  end
end

end

app/views/payments/new.html.haml
.wrapper
  = render "users/header"
  .wrapper__breadcrumb
    - breadcrumb :card
    = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"
  .identification-content
    .credit__container
      .sign-up_main-container-head
        クレジットカード登録
      .sign-up_main-container_registration
        = form_with url: pay_payments_path, method: :post ,id: "charge-form"  do |f|
          .sign-up_main-container_registration-content
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                カード番号
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "半角数字のみ", id: "card_number", name: "number"
              = image_tag src="https://www.sbpayment.jp/images/service/card.png", width: "300", height: "45"
            .sign-up_main-container_registration-content-form
              = f.label :nickname do
                有効期限
              %span{class: "form-require"}必須
              .birthday-select
                .birthday-select-wrap{class: "birthday-select-wrap_month"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :month, ["--", "1", "2", "3", "4", "5", "6", "7","8", "9", "10", "11", "12"], { class: "select" ,id:"exp_month"}
                %span 月
                .birthday-select-wrap{class: "birthday-select-wrap_year"}
                  = icon "fas", "angle-down 2x", class: "icon"
                  = f.select :year, ["--", "2019", "2020", "2021", "2022", "2023", "2024", "2025"], { class: "select" ,id:"exp_year"}
                %span 年
            .sign-up_main-container_registration-content-form{class: "bottom"}
              = f.label :nickname do
                セキュリティーコード
              %span{class: "form-require"}必須
              = f.text_field :nickname, class: "input-default", placeholder: "カード背面4桁もしくは3桁の番号",id: "payment_card_cvc"
            .sign-up_main-container_registration-content-form
              %p
                = link_to "", class: "form-text-blue" do
                  = icon "fas", "question-circle"
                  カード裏面の番号とは？
            .sign-up_main-container_registration-content-form
              =link_to "/payments/show",{controller: "payments", action: "show"} do
                = f.submit "登録", class: "submit-btn",id: "token_submit"
    =render "users/sidebar"        
= render "users/footer"
= render "users/exhibit"           

app/views/payments/show.html.haml
.wrapper
  = render "users/header"
  .wrapper__breadcrumb
    - breadcrumb :card
    = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"
  .identification-content
    -if current_user.payment
      .credit__container
        %h2.chapter__header 支払い方法
        .credit__container-inner
          %section
            %h3.credit__container-inner-content クレジットカード一覧
          %section.user__card
            = form_with url:delete_payments_path, method: :post, id: 'charge-form',  name: "inputForm" do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.deleate 削除する
            .user__card-info
              %span.image
                = image_tag src= "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2394192159 ", width: "49", height: "15"
              %br
              = "**** **** ****" + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
          %section
            = link_to '/', class: "payment__box-content" do
              %span 支払い方法について
    -if current_user.payment == nil
      .credit__container
        %h2.chapter__header 支払い方法
        %h3.credit__container-inner-content クレジットカード一覧
        .logout-box
          .logout-box__btn
            = link_to "/payments/new",{ controller: "payments", action: "show", class:"btn-default btn-red"} do
              クレジットカードを登録する
    =render "users/sidebar"        
  = render "users/footer"
  = render "users/exhibit"   