config/routes.rb
Rails.application.routes.draw do
  # get 'purchase/index'
  # get 'purchase/done'
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection  do
        get 'get_category_children'
        get 'get_category_grandchildren'
      end
  end
  root 'products#index'
  get 'users/:name', controller: 'users', action: 'edit'
  get 'users/identification', to: 'users#edit', as: :identification
  get 'users/exhibiting', to: 'users#edit', as: :exhibiting
  get 'users/profile', to: 'users#edit', as: :profile
  get 'users/logout', to: 'users#edit', as: :logout
  get 'users/show', to: 'users#edit', as: :show
  get 'users/signup', to: 'users#edit', as: :signup

    
  resources :users, only: [:show] 
  resources :payments, only: [:new, :show] do
    collection do
      post 'show', to: 'payments#show'
      post 'pay', to: 'payments#pay'
      post 'delete', to: 'payments#delete'
    end
  end

  # resources :purchase, only: [:index] do
  #   collection do
  #     get 'index', to: 'purchase#index'
  #     post 'pay', to: 'purchase#pay'
  #     get 'done', to: 'purchase#done'
  #   end
  # end
  
  resources :signup,only: [:create] do
    collection do
      get 'member'
      get 'tell'
      get 'address'
      get 'pay' # ここで、入力の全てが終了する
      get 'completion' # 登録完了後のページ
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :transactions
  has_many :users, through: :transactions
  has_many :comments
  has_many :likes
  has_one :street_address
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  belongs_to :category

  with_options presence: true do
    validates :name
    validates :status
    validates :delivery_price
    validates :delivery_way
    validates :scheduled
    validates :text
    validates :prefecture
    validates :category_id
  end

  enum status: {
    "--":0, "新品、未使用":1, "未使用に近い":2, "目立った傷や汚れなし":3, "やや傷や汚れあり":4, "傷や汚れあり":5, "全体的に状態が悪い":6
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy, :show]
  before_action :move_to_index, except: [:index, :show]
  def index
    @products = []
    @products1 = Product.all.includes(:images).order("created_at DESC")
    @products1.each do |product|
      if product.transactions[0].buyer_id == nil
        @products << product
      end
    end
      
  end

  def show
    @seller = User.find(@product.transactions[0]["seller_id"])
    @transaction = Transaction.find_by(product_id: @product.id)
    @category = Category.find(@product.category_id)
    @image = @product.images[0]
    @products = Product.all.includes(:images).order("created_at DESC")
  end

  def new
    @product = Product.new
    @product.images.build
    @category_parent_array = ["--"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
    respond_to do |format|
      format.json 
    end
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
    respond_to do |format|
      format.json 
    end
  end

  def create
    @category_parent_array = ["--"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
    @category = Category.find_by(name: params[:category])
    @product = Product.new(product_params) 
    respond_to do |format|
      if params[:images].blank?
        @product.images.build
        format.html{render action: 'new'}
      else
        @product.category_id = @category.id
        @product.save 
        params[:images][:image].each do |image|
            @product.images.create(image: image, product_id: @product.id)
          end
          @transaction = Transaction.new(product_id: @product.id, seller_id: current_user.id)
          @transaction.save
        format.html{redirect_to products_path}
      end
    end
  end

  def edit
    @seller = User.find(@product.transactions[0]["seller_id"])
    if user_signed_in? && current_user.id == @seller.id
      @category_parent_array = ["--"]
      Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name    
      end
      @product.images[0].image.cache! unless  @product.images[0].image.blank?
    else
      redirect_to root_path
    end
  end

  def update
    @category = Category.find_by(name: params[:category])
    if @product.update(product_params2)
      @product.category_id = @category.id
      if params[:images][:image]
      params[:images][:image].each do |image|
        @product.images.update(image: image, product_id: @product.id)
      end
    else
      params[:images][:default].each do |image|
        @product.images.update(image: image, product_id: @product.id)
    end
  end
      redirect_to product_path(@product[:id])
    else
      render :edit
  end
end

  def destroy
    transaction = Transaction.find(params[:id])
    if user_signed_in? && transaction.seller_id == current_user.id
      @product.delete
    end
    redirect_to root_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :text, :prefecture, :price, :status, :delivery_price, :delivery_way, :scheduled, :category_id, images_attributes:  [:image])
  end

  def product_params2
    params.require(:product).permit(:name, :text, :prefecture, :price, :status, :delivery_price, :delivery_way, :scheduled, :image_cache)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.haml
-@products.each do |product|
  .products_contain_item-box
    = link_to product_path(product), class: "link" do
      .products_contain_item-box-image
        = image_tag product.images[0].image.url
      .products_contain_item-box-body
        .products_contain_item-box-body-name
          = product.name
        .products_contain_item-box-body-under
          .products_contain_item-box-body-under-price
            = "¥#{product.price}"
          .products_contain_item-box-body-under-likes
            = icon "fas",'heart'
            1

app/views/products/edit.html.haml
.contents
  = render "shared/logoheader"
  .contents__main
    .contents__main_block
      .contents__main_block-text 商品の情報を入力
      .contents__main_block_form
        = form_with model: @product, local: true do |f|
          .contents__main_block_form-image
            .contents__main_block_form-image_upload
              .contents__main_block_form-image_upload-text 出品画像
              .focus 必須
            = f.fields_for :images do |image|
              .dropzone-container
                #preview
                .dropzone-area
                  = image.label :image, class: "dropzone-box", for: "upload-image" do
                    .input_area
                      = image.file_field :image, multiple: true, id: "upload-image", name: 'images[image][]',class: "upload-image", 'data-image': 0
                      = image.hidden_field :image_cache, name: 'images[default][]'
                      %pre ドラッグ&ドロップ またはクリックしてファイルをアップロード
                #preview2
                .dropzone-area2
                  = image.label :image, class: "dropzone-box", for: "upload-image" do
                    .input_area
                      = image.file_field :image, multiple: true, id: "upload-image", name: 'images[image][]', class: "upload-image", 'data-image': 0
                      = image.hidden_field :image
                      %pre ここをクリックしてください
          .contents__main_block_form-name
            .product_name
              .product_name-text 商品名
              .focus 必須
            .product_name-form
              = f.text_field :name  ,class: 'input_name', placeholder: "商品名（必須 40文字まで)"
            .product_description
              .product_description-text 商品の説明
              .focus 必須
            .product_description-form
              = f.text_area :text, class: 'input_description', rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          .contents__main_block_form-detail
            .text 商品の詳細
            .detail_box
              .detail-box-wrapper
                .detail_box-category
                  .detail_box-category-text カテゴリー
                  .focus 必須
                .selects
                  = f.select :category_id, @category_parent_array, {}, {class: "selection", id:"category_id"}
                  = icon "fas", "angle-down 2x", class: 'down'
              .detail_box-state
                .detail_box-state-text
                  = @product.status
                .focus 必須
              .selects
                = f.select :status, ["--", "新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], {}, {class: "selection"}
                = icon "fas", "angle-down 2x", class: 'down'
          .contents__main_block_form-about
            .text 配送について
            = link_to "" do
              ?
            .about_box
              .about_box-burden
                .about_box-burden-text 配送料の負担
                .focus 必須
              .selects
                = f.select :delivery_price, ["--", "送料込み(出品者負担)", "着払い(購入者負担)"],{},{class: "selection", id:"delivery_charge"}
                = icon "fas", "angle-down 2x", class: 'down'
              .right-box
                .about_box-way
                  .about_box-way-text 配送の方法
                  .focus 必須
                .selects
                  = f.select :delivery_way,[ "--" ],{},{class: "selection",id:"delivery_way"}
                  = icon "fas", "angle-down 2x", class: 'down'
              .about_box-region
                .about_box-region-text 発送元の地域
                .focus 必須
              .selects 
                = f.collection_select :prefecture, Prefecture.all, :id, :name, {}, {class: "identification-input", id:"prefecture"}
                = icon "fas", "angle-down 2x", class: 'down'
              .about_box-day 
                .about_box-day-text 発送までの日数
                .focus 必須
              .selects
                = f.select :scheduled, ["--", "1~2日で発送", "2~3日で発送", "4~7日で発送"], {} ,{class: "selection", id:"day"}    
                = icon "fas", "angle-down 2x", class: 'down'
          .contents__main_block_form-price
            .text 販売価格(300〜9,999,999)
            = link_to "" do
              ?
            .price_box
              .price_box-price
                .left
                  .left-text 価格
                  .focus 必須
                .right
                  .right-text ¥  
                  .right-form
                    = f.text_field :price, class: 'input_price', placeholder: "例）300"
              .price_box-fee
                .left 販売手数料 (10%)
                .right#sales_charge -
              .price_box-profit
                .left 販売利益
                .right#profit -
          .contents__main_block_form-confirm
            %p
              = link_to "" do
                禁止されている出品
              、
              = link_to "" do
                行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "" do
                偽ブランドの販売
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "" do
                加盟店規約
              に同意したことになります。
              = f.submit  class:"confirm", value:"変更する"
            %button.back 戻る           

  =render "shared/logofooter"

app/views/products/index.html.haml
.top-page_content
  = render "users/header"
  .topic
    %img{src: "//www-mercari-jp.akamaized.net/assets/img/featured/camp/index/index_keyvisual.png?575670517", class: "img"}
  .main_content
    .products
      .products_head
        ピックアップ
      .products_contain
        .products_contain_name
          = link_to "" , class: "link_blue" do
            全ての商品
        .products_contain_item
          = render "products" , collection: @products
          -# = render "products"
        .products_contain_view
          = link_to "", class: "link_blue" do
            全ての商品を見る
  = render "users/footer"
  = render "users/exhibit"

app/views/products/new.html.haml
.contents
  = render "shared/logoheader"
  .contents__main
    .contents__main_block
      .contents__main_block-text 商品の情報を入力
      .contents__main_block_form
        = form_with model: @product, local: true do |f|
          .contents__main_block_form-image
            .contents__main_block_form-image_upload
              .contents__main_block_form-image_upload-text 出品画像
              .focus 必須
            = f.fields_for :images do |image|
              .dropzone-container
                #preview
                .dropzone-area
                  = image.label :image, class: "dropzone-box", for: "upload-image" do
                    .input_area
                      = image.file_field :image, multiple: true, id: "upload-image", name: 'images[image][]',class: "upload-image", 'data-image': 0
                      %pre ドラッグ&ドロップ またはクリックしてファイルをアップロード
                #preview2
                .dropzone-area2
                  = image.label :image, class: "dropzone-box", for: "upload-image" do
                    .input_area
                      = image.file_field :image, multiple: true, id: "upload-image", name: 'images[image][]', class: "upload-image", 'data-image': 0
                      %pre ここをクリックしてください
          .contents__main_block_form-name
            .product_name
              .product_name-text 商品名
              .focus 必須
            .product_name-form
              = f.text_field :name  ,class: 'input_name', placeholder: "商品名（必須 40文字まで)"
            .product_description
              .product_description-text 商品の説明
              .focus 必須
            .product_description-form
              = f.text_area :text, class: 'input_description', rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
          .contents__main_block_form-detail
            .text 商品の詳細
            .detail_box
              .detail-box-wrapper
                .detail_box-category
                  .detail_box-category-text カテゴリー
                  .focus 必須
                .selects
                  = f.select :category_id, @category_parent_array, {}, {class: "selection", id:"category_id"}
                  = icon "fas", "angle-down 2x", class: 'down'
              .detail_box-state
                .detail_box-state-text 商品の状態
                .focus 必須
              .selects
                = f.select :status, Product.statuses.keys, {}, {class: "selection"}
                = icon "fas", "angle-down 2x", class: 'down'
          .contents__main_block_form-about
            .text 配送について
            = link_to "" do
              ?
            .about_box
              .about_box-burden
                .about_box-burden-text 配送料の負担
                .focus 必須
              .selects
                = f.select :delivery_price, ["--", "送料込み(出品者負担)", "着払い(購入者負担)"],{},{class: "selection", id:"delivery_charge"}
                = icon "fas", "angle-down 2x", class: 'down'
              .right-box
                .about_box-way
                  .about_box-way-text 配送の方法
                  .focus 必須
                .selects
                  = f.select :delivery_way,[ "--" ],{},{class: "selection",id:"delivery_way"}
                  = icon "fas", "angle-down 2x", class: 'down'
              .about_box-region
                .about_box-region-text 発送元の地域
                .focus 必須
              .selects 
                = f.collection_select :prefecture, Prefecture.all, :id, :name, {}, {class: "identification-input", id:"prefecture"}
                = icon "fas", "angle-down 2x", class: 'down'
              .about_box-day 
                .about_box-day-text 発送までの日数
                .focus 必須
              .selects
                = f.select :scheduled, ["--", "1~2日で発送", "2~3日で発送", "4~7日で発送"], {} ,{class: "selection", id:"day"}    
                = icon "fas", "angle-down 2x", class: 'down'
          .contents__main_block_form-price
            .text 販売価格(300〜9,999,999)
            = link_to "" do
              ?
            .price_box
              .price_box-price
                .left
                  .left-text 価格
                  .focus 必須
                .right
                  .right-text ¥  
                  .right-form
                    = f.text_field :price, class: 'input_price', placeholder: "例）300"
              .price_box-fee
                .left 販売手数料 (10%)
                .right#sales_charge -
              .price_box-profit
                .left 販売利益
                .right#profit -
          .contents__main_block_form-confirm
            %p
              = link_to "" do
                禁止されている出品
              、
              = link_to "" do
                行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to "" do
                偽ブランドの販売
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to "" do
                加盟店規約
              に同意したことになります。
              = f.submit  class:"confirm", value:"出品する"
            %button.back 戻る           

  =render "shared/logofooter"

app/views/products/purchase.html.haml
.contents
  = render "shared/logoheader"
  .main.single-main
    .purchase-head
      購入内容の確認
    .purchase-products
      .purchase-products__inner
        .purchase-products__image
          = image_tag src= "https://static.mercdn.net/thumb/photos/m21694605444_1.jpg?1565745931" ,width: "64", height: "52.97"}
        .purchase-products__name.bold
          28cm NIKE LD waffle Sacai
        %form.purchase-products__box
          .purchase-products__price.bold
            ¥ 61,500
            %span.purchase-products__shipping-fee
              送料込み
          .purchase-products__toggle
            ポイントはありません
          .purchase-products__cell
            支払い金額
            %span.purchase-products__price-cell ¥ 61,500
          .purchase-products__btn
            = form_tag(action: :pay, method: :post,name: :pay) do
              %button 購入する   
    .purchase-user-info
      .purchase-user-info__delivery 配送先
      .purchase-user-info__zipcode
        〒123-4567
      .purchase-user-info__adress
        大阪府大阪市中央区難波5-1-60 
        %br
        kkkkkk
      %a.purchase-user-info__change-btn
        %span.change-link 変更する
        %i.fa.fa-angle-right
    .purchase-card-info
      .purchase-card-info__pay-fix
        支払い方法
      .purchase-card-info__number
        **** **** **** ****
      .purchase-card-info__expire
        05/24
      .purchase-user-info-card__pay-fix-method
        = image_tag src="/assets/Visa_Inc._logo.svg.png", size: "49x15"
      %a.purchase-user-info__change-btn
        %span.change-link 変更する
        %i.fa.fa-angle-right
  =render "shared/logofooter"

app/views/products/show.html.haml
%header
= render "users/header"

.item
  .item__show
    .item__show_name 
      = @product.name
    .item__show_main
      .item__show_main-photo
        = image_tag @image.image.url, size: "280x280"
      %table.item__show_main-table
        %tbody
          %tr
            %th 
              出品者
            %td
              = link_to "", class: "link_blue" do
                = @seller.nickname
              .ratebox
                .ratings
                  = icon "fas",'smile',class: "smile"
                  %span (^^)
                .ratings
                  = icon "fas", 'meh',class: "meh"
                  %span (;;)
                .ratings
                  = icon 'fas', "angry", class: "angry"
                  %span ('ω')
          %tr
            %th カテゴリー
            %td.category
              = link_to "", class: "link_blue" do
                %div 
                = ">#{@category.parent.parent.name}"
              = link_to "", class: "link_blue" do
                %div 
                = ">#{@category.parent.name}"
              = link_to "", class: "link_blue" do
                %div 
                = ">#{@category.name}"
          %tr
            %th ブランド
            %td 
          %tr
            %th 商品の状態
            %td 
              = @product.status
          %tr
            %th 配送料の負担
            %td
              = @product.delivery_price
          %tr
            %th 配送の方法
            %td 
              = @product.delivery_way
          %tr
            %th 配送元地域
            %td
              = link_to "", class: "link_blue" do
                = @product.prefecture
          %tr
            %th 発送日の目安
            %td
              = @product.scheduled
    .item__show_price
      %span.price 
        = @product.price
      %span.tax (税込)
      %span.fee 送料込み

    - if @transaction.buyer_id.present?
      .item__show_btn
        = link_to "" do
          売り切れました！！
    - else
      .item__show_btn
        = link_to product_purchase_index_path(@product) do
          購入画面に進む
    .item__show_text
      %p.text
        = @product.text
    .item__show_rate
      .left
        %button.left_button
          = icon "fa-heart", class: "like"
          %span いいね！
          %span.amount 0
        .report_button
          = link_to "" do
            = icon "fa-flag", class: "flag"
            %span 不適切な商品の報告
      .right
        = link_to "" do
          = icon "fa-lock", class: "lock"
          %span あんしん・あんぜんへの取り組み
  .item__comments
    .content
      %form
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = text_area_tag "text"
        %button
          %span コメントする
  - if user_signed_in? && current_user.id == @seller.id
    .user_editbox
      = link_to edit_product_path do
        %button.btn-default 商品の編集
    .user_editbox
      = link_to product_path, method: :delete do
        %button.btn-default 商品の削除
  %ul.next
    %li.link-preview
      = link_to "", class: "link_blue" do
        = icon "fa-arrow-left", class: "left"
        路傍の石
    %li.link-next
      = link_to "", class: "link_blue" do
        = icon "fa-arrow-right", class: "right"
        岩
  .item__media
    .content
    %ul.media_box
      %li
        = link_to "" do
          = icon "fab", "facebook", class: "facebook"
      %li
        = link_to "" do
          = icon "fab", "twitter", class: "twitter"
      %li
        = link_to "" do
          = icon "fab", "line", class: "line"
      %li
        = link_to "" do
          = icon "fab", "pinterest", class: "pinterest"
  .item__user
    %section
      .box-head
        = link_to "", class: "link_blue" do
          = "#{@seller.nickname}さんのその他の出品"
      .items-box
        = render "products"
    %section
      .box-head
        = link_to "", class: "link_blue"do
          = "#{@category.parent.parent.name}(#{@category.name})その他の商品"
      .items-box
        = render "products"
  %nav.bottom
    %ul
      %li
        = link_to "" do
          %span メルカリ
        = icon "fas", "arrow-right",class: "arrow-right"  
      %li 
        %span
          = @product.name
%banner
= render "users/footer"